### ISSUE TITLE
Стабильный вылет на янтаре

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [St4lker0k765/shadowcast_engine#4]
При подходе к заводу по заданию "Выключить установку в X16".
`xrEngine.exe caused an EXCEPTION_ACCESS_VIOLATION in module xrGameSOC.dll at 000000000F566C04, vertex_in_direction()+0168 byte(s), E:\stk_old\shadowcast_engine-main\src\xrGameSOC\level_script.cpp, line 0169+0004 byte(s)
stack trace:
0x000000000F566C04 xrGameSOC.dll, vertex_in_direction + 168 byte(s), E:\stk_old\shadowcast_engine-main\src\xrGameSOC\level_script.cpp, 169 + 4 byte(s)
0x000000000F14AF2E xrGameSOC.dll, luabind::detail::free_functions::returns<unsigned int>::callApply<unsigned int,_vector3<float>,float,luabind::detail::primitive_converter<0>,luabind::detail::value_converter<0>,luabind::detail::primitive_converter<0>,0,1,2> + 118 byte(s), E:\stk_old\shadowcast_engine-main\src\3rd party\luabind\include\luabind\function.hpp, 163 + 88 byte(s)
0x000000000F147233 xrGameSOC.dll, luabind::detail::free_functions::call<unsigned int,unsigned int,_vector3<float>,float> + 43 byte(s), E:\stk_old\shadowcast_engine-main\src\3rd party\luabind\include\luabind\function.hpp, 215 + 22 byte(s)
0x00000000C0F2286E lua51.dll
0x00000000C0F27F35 lua51.dll, lua_pcall + 117 byte(s)
0x000000000056FB55 luabind.dll, luabind::detail::pcall + 101 byte(s), E:\stk_old\shadowcast_engine-main\src\3rd party\luabind\src\pcall.cpp, 40 + 17 byte(s)
0x000000000EE40BCF xrGameSOC.dll, luabind::detail::proxy_member_void_caller<>::~proxy_member_void_caller<> + 51 byte(s), E:\stk_old\shadowcast_engine-main\src\3rd party\luabind\include\luabind\detail\call_member.hpp, 269 + 19 byte(s)
0x000000000F487AFB xrGameSOC.dll, CScriptActionWrapper::execute + 47 byte(s), E:\stk_old\shadowcast_engine-main\src\xrGameSOC\script_action_wrapper.cpp, 38
0x000000000F508A7C xrGameSOC.dll, CAI_Stalker::Think + 44 byte(s), E:\stk_old\shadowcast_engine-main\src\xrGameSOC\Ai\Stalker\ai_stalker.cpp, 862
0x000000000F508DBB xrGameSOC.dll, CAI_Stalker::shedule_Update + 619 byte(s), E:\stk_old\shadowcast_engine-main\src\xrGameSOC\Ai\Stalker\ai_stalker.cpp, 780
0x00000000400C3905 xrEngine.exe, CSheduler::ProcessStep + 517 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\xrSheduler.cpp, 366
0x00000000400C3E9B xrEngine.exe, CSheduler::Update + 491 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\xrSheduler.cpp, 485
0x000000000F55C7E3 xrGameSOC.dll, CGamePersistent::OnFrame + 847 byte(s), E:\stk_old\shadowcast_engine-main\src\xrGameSOC\GamePersistent.cpp, 626
0x00000000400402B8 xrEngine.exe, CRegistrator<pureFrame>::Process + 88 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\pure.h, 94
0x000000004003F81C xrEngine.exe, CRenderDevice::FrameMove + 332 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\device.cpp, 490
0x000000004003EC1A xrEngine.exe, CRenderDevice::on_idle + 346 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\device.cpp, 239
0x000000004003F4AF xrEngine.exe, CRenderDevice::message_loop + 111 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\device.cpp, 379
0x000000004003F609 xrEngine.exe, CRenderDevice::Run + 329 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\device.cpp, 423
0x00000000400E5F91 xrEngine.exe, Startup + 417 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\XRayEngine.cpp, 288
0x00000000400E73B5 xrEngine.exe, WinMain_impl + 1557 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\XRayEngine.cpp, 735
0x00000000400E7579 xrEngine.exe, WinMain + 9 byte(s), E:\stk_old\shadowcast_engine-main\src\xrEngine\XRayEngine.cpp, 781
0x0000000040108F5E xrEngine.exe, __scrt_common_main_seh + 262 byte(s), D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, 288 + 33 byte(s)
0x00000000D496257D KERNEL32.DLL, BaseThreadInitThunk + 29 byte(s)
0x00000000D630AF08 ntdll.dll, RtlUserThreadStart + 40 byte(s)
`
Ещё: не могу собрать проект "из коробки". Не хватает DXERR. Приходится постоянно брать эту библиотеку из STCoP-а и самостоятельно добавлять в решение, чтобы его собрать.

**Comment by morrazzzz** [comment]
Модмейкер? Или просто игрок?

**Comment by St4lker0k765** [comment]
Насколько я знаю, на Янтаре попадаются иногда кривые вертексы, которые приводят к вылету игры. Посмотрим, удастся ли это исправить в следующей версии.

**Comment by morrazzzz** [comment]
> Насколько я знаю, на Янтаре попадаются иногда кривые вертексы, которые приводят к вылету игры. Посмотрим, удастся ли это исправить в следующей версии.

Это не похоже на кривые вертексы

**Comment by morrazzzz** [comment]
А в какой момент происходит?

**Comment by OneMorePseudoCoder** [comment]
> Модмейкер? Или просто игрок?

Что-то по середине. Модов особо не делал, но вот движок собрать или чуть-чуть отредактировать. 
Просто по приколу решил на ТЧ накатить и поиграть.
Этот движок собрал с этого коммита [https://github.com/St4lker0k765/shadowcast_engine/commit/4e0c29c2b539546e9fced3d3a525805888c56167](url)
Закинул DXERR с STCoP-а, а то не так движок не собирался. В коде ничего не менял.

> А в какой момент происходит?

![ss_kirill_11-01-24_10-05-30_(l08_yantar)](https://github.com/user-attachments/assets/c42fc37c-38dd-4d00-9599-abb8380cd346)
Пару шагов вперёд - вылет.

Но я через jump_to_level попал на X16. И прошёл её без вылетов.
![ss_kirill_11-01-24_10-10-02_(l08u_brainlab)](https://github.com/user-attachments/assets/d1099de2-15ff-4a2a-91bd-9e0a36f9cfd7)
Прикол такой заметил: разбил ты ящик, а всё добро из него где-то в паре метров от тебя появилось. Не часто происходит, но всё же. Вот в X16 разбил ящики в холе, а все предметы только в коридоре дальше появились.

![ss_kirill_11-01-24_10-15-54_(l08u_brainlab)](https://github.com/user-attachments/assets/4a1aee54-effb-44b4-a6b2-3303942ec41c)
Ещё после добавления ЗП системы оружия у вас анимации у магазинного ТЧ (Калаши, ЭМ-ки, Гроза и т.п.) оружия сломались: анимация бега не проигрывается, а на скрине выше пример сломанного прицеливания из винтовки с подствольником.

**Comment by morrazzzz** [comment]
> > Модмейкер? Или просто игрок?
> 
> Что-то по середине. Модов особо не делал, но вот движок собрать или чуть-чуть отредактировать. Просто по приколу решил на ТЧ накатить и поиграть. Этот движок собрал с этого коммита [https://github.com/St4lker0k765/shadowcast_engine/commit/4e0c29c2b539546e9fced3d3a525805888c56167](url) Закинул DXERR с STCoP-а, а то не так движок не собирался. В коде ничего не менял.
> 
> > А в какой момент происходит?
> 
> ![ss_kirill_11-01-24_10-05-30_(l08_yantar)](https://private-user-images.githubusercontent.com/73041211/382214600-c42fc37c-38dd-4d00-9599-abb8380cd346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDcyNDIsIm5iZiI6MTczMDQ0Njk0MiwicGF0aCI6Ii83MzA0MTIxMS8zODIyMTQ2MDAtYzQyZmMzN2MtMzhkZC00ZDAwLTk1OTktYWJiODM4MGNkMzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA3NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjBmMTJiNWY5MzU1MzFmYWI5ZGZhMjE4ZjcxNTllOWRjZWUzNWI1OTBhOTUzNjk5YzRhYzg0MzE1NTRlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.urqmPjQmhk8i5czT-nHvXfCEHUK9dnxbeYM8qU5enLg) Пару шагов вперёд - вылет.
> 
> Но я через jump_to_level попал на X16. И прошёл её без вылетов. ![ss_kirill_11-01-24_10-10-02_(l08u_brainlab)](https://private-user-images.githubusercontent.com/73041211/382215037-d1099de2-15ff-4a2a-91bd-9e0a36f9cfd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDcyNDIsIm5iZiI6MTczMDQ0Njk0MiwicGF0aCI6Ii83MzA0MTIxMS8zODIyMTUwMzctZDEwOTlkZTItMTVmZi00YTJhLTkxYmQtOWUwYTM2ZjljZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA3NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMmUwYmIyYzBjMTliYjIzYTczNmU2ZmQzNzM0YmQ0MjY1M2Y1NTE3NThhYjdhYTFlMDNkZGVmNThjOTNhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f3PHgYNeW5f6m46uW8cdZx-n-6C5FmQuQiXjZ89KA0M) Прикол такой заметил: разбил ты ящик, а всё добро из него где-то в паре метров от тебя появилось. Не часто происходит, но всё же. Вот в X16 разбил ящики в холе, а все предметы только в коридоре дальше появились.
> 
> ![ss_kirill_11-01-24_10-15-54_(l08u_brainlab)](https://private-user-images.githubusercontent.com/73041211/382215515-4a1aee54-effb-44b4-a6b2-3303942ec41c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDcyNDIsIm5iZiI6MTczMDQ0Njk0MiwicGF0aCI6Ii83MzA0MTIxMS8zODIyMTU1MTUtNGExYWVlNTQtZWZmYi00NGI0LWE2YjItMzMwMzk0MmVjNDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA3NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NmJlNmY3ZmEzZDBhOWVmMzgwZmQ4OTFhMjMzYzU5NzViNWU5M2JiMjFkYjY5OGZmOTczNjNkZTA3YWM2ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EJxlpOU58nVHdIVcikrYJUCyFUq4syZE-BhWYiiwxYk) Ещё после добавления ЗП системы оружия у вас анимации у магазинного ТЧ (Калаши, ЭМ-ки, Гроза и т.п.) оружия сломались: анимация бега не проигрывается, а на скрине выше пример сломанного прицеливания из винтовки с подствольником.

Так как в этом движке модуль xrGame был взят от моего движка. И если @St4lker0k765 сделаем мне плеер худ, я смогу определить с этим все баги и пофиксить куча других. Насчет бага с ящиками, это пофикситься, только чуть попозже. На Янтаре тоже посмотрю на этот вылет

**Comment by morrazzzz** [comment]
Спасибо за кучу баг репортов :)

**Comment by St4lker0k765** [comment]
На данный момент практически все баги (кроме бага с ящиками) исправлены.
